### ISSUE TITLE
Ratpack Server in Server Field

### ISSUE THREAD

**Issue by PKuhn** [HPI-SWA-Teaching/SWT15-Project-01#11]

**Comment by PKuhn** [comment]
As a user of a ratpack application I want to have the server field set to the specific application in responses

**Comment by fniephaus** [comment]
https://www.hpi.uni-potsdam.de/hirschfeld/trac/SqueakCommunityProjects/wiki/squeak_faq#WieversioniertmanMethodeninfremdenoderSqueak-eigenenKlassen
