### ISSUE TITLE
Session Middleware [13+3]

### ISSUE THREAD

**Issue by essal0815** [HPI-SWA-Teaching/SWT15-Project-01#112]
### Subject
A middleware for session management. Handling sessions via Json-Web-Tokens (JWT).

### Details
The usecase for this issue is that we want to implement authentication middleware in future and need session handling first.

There is a Package `Cryptography` in Squeak where several cipher and hash methods are already implemented.
Base64 encoding is implemented in class `String`.

#### preHook
   - [ ] reads JWT from header field
      - [ ] if authorization header is empty, new empty JWT token is generated
   - [ ] creates data object (parsed JWT token)
   - [ ] validates against signature
      - [ ] if validation fails an empty data object shall be saved to dynamicEnvironment
   - [ ] saves object in the dynamicEnvironment

#### postHook
   - [ ] retrieve object from dynamicEnvironment
   - [ ] encode object data
   - [ ] create signature
   - [ ] put new JWT in HTTP response

### Efford estimation
13 - in team during customer session

**Comment by skydivin4ng3l** [comment]
What is still to do in this issue?
