### ISSUE TITLE
remove unnessecary debug prints

### ISSUE THREAD

**Issue by PKuhn** [HPI-SWA-Teaching/SWT15-Project-01#23]
As a ratpack developer I want to remove unnecessary warnings to debug my code more easily

**Comment by PKuhn** [comment]
As a ratpack developer I want to remove unnecessary warnings to debug my code more easily

**Comment by ratnim** [comment]
Warnings are seen in the Transcript.

**Comment by lawrencebenson** [comment]
It seems to be a threading issue, possibly a race condition. The statements like `RPApplication>>DoItIn: (id is Undeclared) `  seem to be legit and not for debug resons as expected.
