### ISSUE TITLE
Application registration

### ISSUE THREAD

**Issue by StarkRobert** [HPI-SWA-Teaching/SWT15-Project-01#3]
Als RatPack-Entwickler möchte ich eine Klasse in meiner RatPack-Applikation registrieren, damit sie von außen erreichbar ist.

4h ratnim

**Comment by ratnim** [comment]
Wrote small ClassObject class with instatiation method for strings, a small validator method and stringify method.

**Comment by ratnim** [comment]
TestGetRegisteredClassWithString need some further work.
"Catch the expected Signals"
