### ISSUE TITLE
add Object through endpoint

### ISSUE THREAD

**Issue by StarkRobert** [HPI-SWA-Teaching/SWT15-Project-01#5]
Als API-Nutzer möchte ich über ein Endpoint ein neues Objekt erzeugen können mit Validierung.

**Comment by StarkRobert** [comment]
start with insert

add-on: get, list, delete

**Comment by StarkRobert** [comment]
Need Issue 6 and 7

**Comment by PKuhn** [comment]
- [ ] test
- [ ] test2

**Comment by PKuhn** [comment]
As user of a ratpack application I want to send a POST request to /API/ModelName to create a new Object of this Model
